export const environment = {
  apiUrl: 'http://localhost:8081',
  isAutoLoadEnabled: true,
  autoLoadTime: 1000,
  categoriesPerRequest: 100,
  tagsPerRequest: 100,
  resultsPerSearch: 100,
  checkIsJobRunningTime: 5000,
  LIMIT_EXPLORER_BY_TAG: 100,
  LIMIT_EXPLORER_BY_CATEGORY: 100,
  LIMIT_EXPLORER_BY_EXTENSION: 100,
  LIMIT_EXPLORER_BY_EXPLORER: 100,
  LIMIT_EXPLORER_BY_PUBLISHER: 100,
  LIMIT_EXPLORER_BY_LANGUAGE: 100,
  LIMIT_EXPLORER_BY_PUBLISHED_DATE: 100,
  LIMIT_EXPLORER_BY_RATING: 100,
};
